In [43]:
import pandas as pd

In [44]:
#Задание1
ratings = pd.read_csv('ml-latest-small/ratings.csv')
movies = pd.read_csv('ml-latest-small/movies.csv')

In [45]:
df = ratings.merge(movies, on='movieId', how='left')
df.head()

,userId,movieId,rating,timestamp,title,genres
0,1,1,4.0,964982703,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,1,3,4.0,964981247,Grumpier Old Men (1995),Comedy|Romance
2,1,6,4.0,964982224,Heat (1995),Action|Crime|Thriller
3,1,47,5.0,964983815,Seven (a.k.a. Se7en) (1995),Mystery|Thriller
4,1,50,5.0,964982931,"Usual Suspects, The (1995)",Crime|Mystery|Thriller

In [46]:
df = df.filter(items = ['title', 'rating'])
df.head()

                         title  rating
0             Toy Story (1995)     4.0
1      Grumpier Old Men (1995)     4.0
2                  Heat (1995)     4.0
3  Seven (a.k.a. Se7en) (1995)     5.0
4   Usual Suspects, The (1995)     5.0

In [47]:
new_df = df[df['rating'] == 5.0]
#new_df
new_df.groupby('title').count().sort_values('rating', ascending=False).head()

                                           rating
title
Shawshank Redemption, The (1994)              153
Pulp Fiction (1994)                           123
Forrest Gump (1994)                           116
Matrix, The (1999)                            109
Star Wars: Episode IV - A New Hope (1977)     104

In [48]:
#Задание2
power = pd.read_csv('power.csv')
power.head()

   country  year  quantity  category
0  Austria  1996       5.0         1
1  Austria  1995      17.0         1
2  Belgium  2014       0.0         1
3  Belgium  2013       0.0         1
4  Belgium  2012      35.0         1

In [49]:
new_power = power[(((power['country']=='Latvia') | (power['country']=='Lithuania') | (power['country']=='Estonia')) & ((power['category'] == 4) | (power['category'] == 12)  | (power['category'] == 21)) & ((power['year'] >= 2005) & (power['year'] <= 2010)) & (power['quantity'] >= 0))]
result = new_power.filter(items = ['country', 'quantity']).groupby('country').sum()
result

           quantity
country
Estonia     63440.0
Latvia      54844.0
Lithuania  122296.0

In [50]:
#Задание3
page_url = 'https://www.finanz.ru/valyuty/v-realnom-vremeni'

In [51]:
df_my = pd.read_html(page_url, encoding='utf-8')
new_df = df_my[1]
new_df = new_df.filter(items = ['Рубль', 'Предложение', 'Спрос', 'Предыдущее закрытие', '%', 'Абсолютное значение', 'Время'])
new_df

,Рубль,Предложение,Спрос,Предыдущее закрытие,%,Абсолютное значение,Время
0,GBP/RUB,1006495,-,1006495,"0,00 %",00000,17.10.2020
1,EUR/RUB,911850,-,911850,"0,00 %",00000,17.10.2020
2,USD/RUB,779262,-,779745,"-0,06 %",-00483,17.10.2020
3,JPY/RUB,07393,-,07394,"0,00 %",00000,17.10.2020
4,CNY/RUB,116347,-,116349,"0,00 %",-00003,17.10.2020
5,CHF/RUB,851960,-,851839,"0,01 %",00121,17.10.2020
6,Евро,Предложение,Спрос,Предыдущее закрытие,%,Абсолютное значение,Время
7,EUR/USD,11717,-,11710,"0,06 %",00007,17.10.2020
8,EUR/GBP,09072,-,09072,"0,00 %",00000,17.10.2020
9,EUR/JPY,1235150,-,1235000,"0,01 %",00150,17.10.2020
10,EUR/CHF,10743,-,10709,"0,32 %",00034,17.10.2020
11,Доллар США,Предложение,Спрос,Предыдущее закрытие,%,Абсолютное значение,Время
12,USD/EUR,08535,-,08535,"0,00 %",00000,17.10.2020
13,USD/GBP,07742,-,07742,"0,00 %",00000,17.10.2020
14,USD/JPY,1054000,-,1054000,"0,00 %",00000,17.10.2020
15,USD/CHF,09147,-,09148,"-0,01 %",-00001,17.10.2020
16,Японская иена,Предложение,Спрос,Предыдущее закрытие,%,Абсолютное значение,Время
17,JPY/EUR (100:1),08100,-,08100,"0,00 %",00000,17.10.2020
18,JPY/GBP,00074,-,00074,"0,00 %",00000,17.10.2020
19,JPY/USD,00095,-,00095,"0,00 %",00000,17.10.2020
20,JPY/CHF (100:1),08700,-,08700,"0,07 %",00000,17.10.2020
21,Фунт стерлингов,Предложение,Спрос,Предыдущее закрытие,%,Абсолютное значение,Время
22,GBP/USD,12916,-,12916,"0,00 %",00000,17.10.2020
23,GBP/JPY,1361347,-,1361282,"0,00 %",00065,17.10.2020
24,GBP/EUR,11022,-,11024,"-0,02 %",-00003,17.10.2020
25,GBP/CHF,11815,-,11814,"0,00 %",00001,17.10.2020
26,Швейцарский франк,Предложение,Спрос,Предыдущее закрытие,%,Абсолютное значение,Время
27,GBP/CHF,11815,-,11814,"0,00 %",00001,17.10.2020
28,EUR/CHF,10743,-,10709,"0,32 %",00034,17.10.2020
29,JPY/CHF (100:1),08700,-,08700,"0,07 %",00000,17.10.2020
30,USD/CHF,09147,-,09148,"-0,01 %",-00001,17.10.2020
31,Украинская гривна,Предложение,Спрос,Предыдущее закрытие,%,Абсолютное значение,Время
32,EUR/UAH,331990,-,332298,"-0,09 %",-00307,17.10.2020
33,USD/UAH,283353,-,283615,"-0,09 %",-00263,17.10.2020
34,CHF/UAH,309788,-,310030,"-0,08 %",-00242,17.10.2020
35,GBP/UAH,365980,-,366317,"-0,09 %",-00338,17.10.2020